import type { NextPage } from "next";
import Head from "next/head";
import { Movie } from "../../typings";
import Header from "../components/Header";
import Nav from "../components/Nav";
import Results from "../components/Results";
import requests, { BASE_URL } from "../utils/requests";

const Home = ({ results }: { results: Movie[] }) => {
  return (
    <div className="">
      <Head>
        <title>Hulu</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Header />

      <Nav />

      <Results results={results} />
    </div>
  );
};

export async function getServerSideProps(context: any) {
  const gener = context.query.gener;
  if (gener) {
    //@ts-ignore
    const res = await fetch(requests[gener]?.url).then((res) => res.json());
    return { props: { results: res.results } };
  } else {
    const res = await fetch(`${requests.fetchTrending.url}`).then((res) =>
      res.json()
    );
    return { props: { results: res.results } };
  }
}

export default Home;
